### ISSUE TITLE
.htaccess wrong directory basis on localhost

### ISSUE THREAD

**Issue by ihabovich** [atmoner/Bittytorrent#11]
I use version 1.1, which I face some issue caused by .htaccess RewriteRule for all sub directories.
Ex. I go to Torrents link in top header (http://localhost/sitename//torrents), some how I use my WAMP server localhost index where my address bar has URL: http://localhost/sitename/torrents. Any help is much appreciated.

**Comment by atmoner** [comment]
yep! I code the site to be on a main domain (or subdomain) but I know that bittytorrent user has ever had this problem and have already settle it succeeds in http://forum.bittytorrent.com/installed-but-links-are-broken-t179.html

**Comment by ihabovich** [comment]
I can`t see a solution in your shared link. Any suggestions?

**Comment by atmoner** [comment]
first comment edited with the good htaccess

**Comment by ihabovich** [comment]
Since all my trials went for failure, you may share final .htaccess full coding :)

**Comment by atmoner** [comment]
Try this:
```
RewriteEngine on
RewriteCond %{HTTP_HOST} ^localhost$
RewriteCond %{REQUEST_URI} !^/sitename/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /Bittytorrent/$1
RewriteCond %{HTTP_HOST} ^localhost$
RewriteRule ^(/)?$ sitename/index.php [L]


RewriteRule ^([^/]*)$ /?page=$1 [L,QSA]
RewriteRule ^([^-]*)/([^-]*)/$ ?page=$1&act=$2 [QSA,L]
 
 
RewriteRule ^upload/([^/]*)$ /?page=upload&act=$1 [L]
RewriteRule ^torrents/([0-9]+)$ /?page=torrents&next=$1 [L,QSA] 
RewriteRule ^torrents/cat/([^/]*)$ /?page=torrents&catid=$1 [L,QSA]
RewriteRule ^torrents/cat/([^/]*)/([^/]*)$ /?page=torrents&catid=$1&next=$2 [L,QSA]  
RewriteRule ^torrents/search/([^/]*)$ /?page=torrents&search=$1 [L,QSA] 
RewriteRule ^torrents/([^/]*)/([^/]*)$ /?page=torrents&sortedBy=$1&axis=$2 [L,QSA] 
RewriteRule ^torrents/([^/]*)/([^/]*)/([^/]*)$ /?page=torrents&next=$1&sortedBy=$2&axis=$3 [L,QSA]  
RewriteRule ^torrents/cat/([^/]*)/([^/]*)/([^/]*)$ /?page=torrents&catid=$1&sortedBy=$2&axis=$3 [L,QSA]
RewriteRule ^torrents/cat/([^/]*)/([^/]*)/([^/]*)/([^/]*)$ /?page=torrents&catid=$1&next=$2&sortedBy=$3&axis=$4 [L,QSA]
RewriteRule ^torrent-detail/([^/]*)$ /?page=torrent-detail&id=$1 [L,QSA] 
RewriteRule ^torrent-detail/([^/]*)/([^/]*)$ /?page=torrent-detail&id=$1&urlTitle=$2 [L,QSA] 
RewriteRule ^torrent-edit/([^/]*)/([^/]*)$ /?page=torrent-edit&id=$1&urlTitle=$2 [L]
RewriteRule ^torrent-delete/([^/]*)/([^/]*)$ /?page=torrent-delete&id=$1&hash=$2 [L]
RewriteRule ^download/([^/]*)$ /?page=download&hash=$1 [L]
RewriteRule ^rss/([^/]*)$ /?page=rss&cat=$1 [L]
RewriteRule ^account/([0-9]+)$ /?page=account&next=$1 [QSA,L]
RewriteRule ^admincp/users/([0-9]+)$ /?page=admincp&act=users&next=$1 [QSA,L]
```

**Comment by ihabovich** [comment]
Now I am getting 404 for index!

**Comment by atmoner** [comment]
So install it on main domain or sub domain

**Comment by ihabovich** [comment]
That was disappointing. Development can not be managed on hosted servers ;)

**Comment by atmoner** [comment]
what?! Create a subdomain !! this is free and costs nothing !! 

it is also often as that one works in development mode! If you change the script so it runs in a subfolder (in development) you will be forced to retrace your steps to move for the public, is not how we work in development mode ....

And I've said from the beginning, the script is not designed to work in sub folder, the problem will not s only the .htaccess but every link of the site will also obsolete!

So working on the script with a sub domain and not in a sub folder !!

**Comment by ihabovich** [comment]
I was able to configuring my virtual host, assigning a domain name. Cheers :+1: 
http://stackoverflow.com/questions/13529006/wamp-in-network-with-a-domain-name
