### ISSUE TITLE
Problem to connect

### ISSUE THREAD

**Issue by Kcchouette** [atmoner/Bittytorrent#13]
Hey

My instance bittytorrent is located in `http://localhost:8080/Bittytorrent-Test/index.php`.

I can't login because it redirect me to `http://localhost:8080/login Failed to load resource: the server responded with a status of 404 (Not Found)` (that normal, Bittytorrent is located in the Bittytorrent-Test folder)

In my database, baseurl is ok: SELECT `value `FROM `settings` where `key` = "baseurl"; is equal to 
`http://localhost:8080/Bittytorrent-Test`

**Comment by atmoner** [comment]
Yep, you must adjust it in .htaccess file.
This part:
```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^/index\.
RewriteCond %{REQUEST_URI} !^/$
```

Like this:
```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^Bittytorrent-Test/index\.
RewriteCond %{REQUEST_URI} !^Bittytorrent-Test/$
```
