### ISSUE TITLE
Issue uploading

### ISSUE THREAD

**Issue by spun2u** [atmoner/Bittytorrent#14]
I seem to have everything configured until I tried uploading a test torrent. This is what I get:

Warning: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `leechers`=leechers+, `finished`=finished+, `last_scrape`='1517103370' WHERE `i' at line 1 in /home/trac/public_html/libs/database/ez_sql_mysqli.php on line 272

Warning: Cannot modify header information - headers already sent by (output started at /home/trac/public_html/libs/database/ez_sql_mysqli.php:272) in /home/trac/public_html/libs/default.class.php on line 1103

**Comment by atmoner** [comment]
this project is obsolete! the support is no longer maintained, sorry (I really do not have time for that)
