### ISSUE TITLE
Cross site elements in bittytorrent

### ISSUE THREAD

**Issue by nazmifr** [atmoner/Bittytorrent#3]
Hi,
I'm planning on making use of the bittytorrent system to build a torrent sharing site (for legal content of course (to be precise, sharing some content I (and a few friends) make without overloading my personnal server))

So I made a simple install of the tool on one of my servers and I noticed some external elements coming from boostrapcdn and raw.githubusercontent.com, I'd like to point out the fact that it might be risky on a privacy and a durability ground and it makes the users of bittytorrent dependent from those services.

From a rapid look in the code, it's just a matter of a font from bootstrapcdn and some javascript 'lightbox' from github.

Of course for my use it's not a problem, though I'll recover the two objects, host them on my server and edit the pages, but it would be great if you changed it directly in the code of bittytorrent (unless it has already been done or there are some other reasons that justify it)

Anyway, thanks a lot for that awesome project of yours and I look forward to the further development you might make and your answer about my suggestion.

**Comment by atmoner** [comment]
Hi!
Yes, there are some things to call from the outside! It can be easily corrected (and I would do that I could) I am not at home right now but I do not want to stay in my life! 
Thank you for pointing this concern.

**Comment by nazmifr** [comment]
Thanks for your answer and for having considered it ^^

**Comment by anonymiz** [comment]
one of the lazy developer in the world

**Comment by atmoner** [comment]
@anonymiz  I do not have time anymore! you want to retrived the project?

**Comment by nazmifr** [comment]
I'd be glad to help with what I can.

**Comment by nazmifr** [comment]
There is a need for such a CMS

**Comment by nazmifr** [comment]
I mean, in france we don't have a torrent tracker anymore, a free CMS like that would make new trackers pop...

**Comment by atmoner** [comment]
No Time.... Sorry
