### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by fmohican** [atmoner/Bittytorrent#4]
It's there any chance for nginx support ?

( https://en.wikipedia.org/wiki/Nginx )

**Comment by atmoner** [comment]
@fmohican must be work with small change on .htaccess file! 
Try this one convertor:  

http://www.anilcetin.com/  
or  
https://winginx.com/en/htaccess

**Comment by fmohican** [comment]
Okay i will try,
i will replay soon if work or no

**Comment by fmohican** [comment]
Nope, Not working. still broke nginx

**Comment by atmoner** [comment]
@fmohican give me more information please
