### ISSUE TITLE
your website is not working

### ISSUE THREAD

**Issue by princev558** [atmoner/Bittytorrent#5]
hi,
i tried to access your website, but i am not able to access your website. so can you please check your website.
I need to setup disqus comment system so please help me

**Comment by FranceBB** [comment]
Still not working. C'mon, I was waiting for the RSS automatic uploader you were developing... :(

**Comment by atmoner** [comment]
@princev558 @FranceBB I am not available until June 15! And I have no way to put the site online from where I am  
But a little patience, I take care to put the site online as soon as possible!
Thank you for your understanding!  

Ps: @FranceBB All the code for RSS auto upload are on my computer several thousand miles from me but they are almost ready! You will be the first to know when I would have returned

**Comment by FranceBB** [comment]
It's almost June 15, time has almost come. I've been looking forward for this moment. :D 
Oh, one more thing; this is the site I would like to rip torrent: https://nyaa.si/
I mean, like every torrent uploaded in this site, by any user. It's the largest public anime torrent site. If I can rip torrents uploaded there, I would reach thousands and thousands of users. (my users are as little as 6000-7000 per day, right now).

**Comment by FranceBB** [comment]
June 20. Any news? Are you back? Sorry for bothering you, but I really really care about bittytorrent and I look forward for you to be back online. :)

**Comment by atmoner** [comment]
sorry for the wait!!  I retrieve the original domain name from bittytorrent
[http://bittytorrent.com/](http://bittytorrent.com/)  
I must reinstall everything and I can get back to work ;)

**Comment by atmoner** [comment]
And the forum is back!! http://forum.bittytorrent.com/

**Comment by Chouchen** [comment]
Suspended.

**Comment by NANO-Chile** [comment]
http://bittytorrent.com/ says "SOON" now.

When will be available? can we see a demo site at some other place?

**Comment by atmoner** [comment]
Forum online! 
Thank you for giving me a little time to put everything online

**Comment by NANO-Chile** [comment]
@atmoner what about the demo? :(

**Comment by spun2u** [comment]
@atmoner any ideas where I can find the db.php file that should be in the libs/ directory? Can install without it.

**Comment by mikail97** [comment]
@atmoner where can I fin the libs/db.php ? I cant install without it, please give some help here and your website and forum doesn't work.

**Comment by atmoner** [comment]
@mikail97 @spun2u db.php is here: https://github.com/atmoner/Bittytorrent/commit/911dcadb71363ee8de8d5ded6f898cf50af130b6

**Comment by atmoner** [comment]
Ok! Website work fine now
