### ISSUE TITLE
[Bug] Wrong Filesize after 2GB

### ISSUE THREAD

**Issue by DoM1niC** [atmoner/Bittytorrent#7]
If my files bigger than 2 GB, its show only 2GB not the corrrect Filesize....

**Comment by atmoner** [comment]
the function used to calculate the size of a torrent content is: [bytesToSize()](https://github.com/atmoner/Bittytorrent/blob/master/libs/default.class.php#L399) 
But I do not understand why he does not calculate decimal :/

**Comment by mguennec** [comment]
MySQL INT maximum value is 2147483647 which equals 2GB. (`size` int(11) NOT NULL)

**Comment by atmoner** [comment]
Bug fixed: 1c19abe857cdf66e8c5965b6e22cebef7b14f7ea
